import { cpSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { base, color, primitives, tone } from "../src/tokens.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "dist");
mkdirSync(resolve(dist, "presets"), { recursive: true });

const alias = /^\{([a-z]+)\.(\w+)\}$/;
const toCssValue = (v) => {
  const m = typeof v === "string" && v.match(alias);
  return m ? `var(--tk-${m[1]}-${m[2]})` : v;
};

function cssForValue(t) {
  const v = t.$value;
  if (t.$type === "shadow")
    return v.map((s) => `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`).join(", ");
  if (t.$type === "cubicBezier") return `cubic-bezier(${v.join(", ")})`;
  return String(v);
}

function themeBlock(mode) {
  const lines = [];
  for (const [k, v] of Object.entries(color[mode]))
    lines.push(`  --tk-color-${k}: ${toCssValue(v)};`);
  for (const [k, [bg, fg]] of Object.entries(tone[mode])) {
    lines.push(`  --tk-tone-${k}-bg: ${toCssValue(bg)};`);
    lines.push(`  --tk-tone-${k}-fg: ${toCssValue(fg)};`);
  }
  // Scheme switches for content that has a light and a dark variant (avatar.imageDarkField).
  lines.push(`  --tk-scheme-light-display: ${mode === "light" ? "block" : "none"};`);
  lines.push(`  --tk-scheme-dark-display: ${mode === "dark" ? "block" : "none"};`);
  lines.push(`  color-scheme: ${mode};`);
  return lines.join("\n");
}

// ---- CSS -------------------------------------------------------------------
const prim = [];
for (const [group, steps] of Object.entries(primitives))
  for (const [step, hex] of Object.entries(steps)) prim.push(`  --tk-${group}-${step}: ${hex};`);

const baseLines = [];
for (const [group, tokens] of Object.entries(base))
  for (const [name, t] of Object.entries(tokens))
    baseLines.push(`  --tk-${group}-${name}: ${cssForValue(t)};`);

const css = `/* @tablekit/tokens — generated by scripts/build.mjs. Do not edit by hand. */
/*
 * Everything here uses :where() (zero specificity), so any preset or your own
 * :root { --tk-… } overrides win regardless of import order.
 *
 * Theme switching:
 *   - follows prefers-color-scheme by default
 *   - force with data-tk-theme="light|dark" on any ancestor
 *   - also honors the common conventions data-theme="light|dark" and .light / .dark
 */

:where(:root) {
${prim.join("\n")}
${baseLines.join("\n")}
}

:where(:root, [data-tk-theme="light"], [data-theme="light"], .light) {
${themeBlock("light")}
}

@media (prefers-color-scheme: dark) {
  :where(:root:not([data-tk-theme="light"], [data-theme="light"], .light)) {
${themeBlock("dark").replace(/^/gm, "  ")}
  }
}

:where([data-theme="dark"], .dark, [data-tk-theme="dark"]) {
${themeBlock("dark")}
}
`;
writeFileSync(resolve(dist, "tokens.css"), css);

// ---- DTCG JSON (Tokens Studio / Style Dictionary / Figma variables) ------------
const dtcgPrimitives = {};
for (const [group, steps] of Object.entries(primitives)) {
  dtcgPrimitives[group] = {};
  for (const [step, hex] of Object.entries(steps))
    dtcgPrimitives[group][step] = { $type: "color", $value: hex };
}
const dtcgTheme = (mode) => ({
  color: Object.fromEntries(
    Object.entries(color[mode]).map(([k, v]) => [k, { $type: "color", $value: v }]),
  ),
  tone: Object.fromEntries(
    Object.entries(tone[mode]).map(([k, [bg, fg]]) => [
      k,
      { bg: { $type: "color", $value: bg }, fg: { $type: "color", $value: fg } },
    ]),
  ),
});

const json = {
  $description:
    "tablekit design tokens (W3C DTCG). Token sets: primitives, base, light, dark. CSS name = --tk-<path joined by ->.",
  primitives: dtcgPrimitives,
  base,
  light: dtcgTheme("light"),
  dark: dtcgTheme("dark"),
  $themes: [
    {
      name: "Light",
      selectedTokenSets: { primitives: "source", base: "enabled", light: "enabled" },
    },
    { name: "Dark", selectedTokenSets: { primitives: "source", base: "enabled", dark: "enabled" } },
  ],
};
writeFileSync(resolve(dist, "tokens.json"), `${JSON.stringify(json, null, 2)}\n`);

// ---- Presets ---------------------------------------------------------------
for (const f of readdirSync(resolve(root, "src/presets")))
  cpSync(resolve(root, "src/presets", f), resolve(dist, "presets", f));

console.log("tokens: wrote dist/tokens.css, dist/tokens.json, dist/presets/*");
